services:
  mysql:
    image: mysql:8.4
    container_name: store-rating-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store_rating_platform
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
